/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.digest.activity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DigestConfiguration service. Represents a row in the &quot;Digest_DigestConfiguration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.digest.activity.model.impl.DigestConfigurationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.digest.activity.model.impl.DigestConfigurationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DigestConfiguration
 * @see com.liferay.portlet.digest.activity.model.impl.DigestConfigurationImpl
 * @see com.liferay.portlet.digest.activity.model.impl.DigestConfigurationModelImpl
 * @generated
 */
public interface DigestConfigurationModel extends BaseModel<DigestConfiguration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a digest configuration model instance should use the {@link DigestConfiguration} interface instead.
	 */

	/**
	 * Returns the primary key of this digest configuration.
	 *
	 * @return the primary key of this digest configuration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this digest configuration.
	 *
	 * @param primaryKey the primary key of this digest configuration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this digest configuration.
	 *
	 * @return the ID of this digest configuration
	 */
	public long getId();

	/**
	 * Sets the ID of this digest configuration.
	 *
	 * @param id the ID of this digest configuration
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this digest configuration.
	 *
	 * @return the company ID of this digest configuration
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this digest configuration.
	 *
	 * @param companyId the company ID of this digest configuration
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this digest configuration.
	 *
	 * @return the create date of this digest configuration
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this digest configuration.
	 *
	 * @param createDate the create date of this digest configuration
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this digest configuration.
	 *
	 * @return the modified date of this digest configuration
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this digest configuration.
	 *
	 * @param modifiedDate the modified date of this digest configuration
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group ID of this digest configuration.
	 *
	 * @return the group ID of this digest configuration
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this digest configuration.
	 *
	 * @param groupId the group ID of this digest configuration
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this digest configuration.
	 *
	 * @return the user ID of this digest configuration
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this digest configuration.
	 *
	 * @param userId the user ID of this digest configuration
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this digest configuration.
	 *
	 * @return the user uuid of this digest configuration
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this digest configuration.
	 *
	 * @param userUuid the user uuid of this digest configuration
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the enabled of this digest configuration.
	 *
	 * @return the enabled of this digest configuration
	 */
	public boolean getEnabled();

	/**
	 * Returns <code>true</code> if this digest configuration is enabled.
	 *
	 * @return <code>true</code> if this digest configuration is enabled; <code>false</code> otherwise
	 */
	public boolean isEnabled();

	/**
	 * Sets whether this digest configuration is enabled.
	 *
	 * @param enabled the enabled of this digest configuration
	 */
	public void setEnabled(boolean enabled);

	/**
	 * Returns the frequency of this digest configuration.
	 *
	 * @return the frequency of this digest configuration
	 */
	public int getFrequency();

	/**
	 * Sets the frequency of this digest configuration.
	 *
	 * @param frequency the frequency of this digest configuration
	 */
	public void setFrequency(int frequency);

	/**
	 * Returns the scope group ID of this digest configuration.
	 *
	 * @return the scope group ID of this digest configuration
	 */
	public long getScopeGroupId();

	/**
	 * Sets the scope group ID of this digest configuration.
	 *
	 * @param scopeGroupId the scope group ID of this digest configuration
	 */
	public void setScopeGroupId(long scopeGroupId);

	/**
	 * Returns the scope user ID of this digest configuration.
	 *
	 * @return the scope user ID of this digest configuration
	 */
	public long getScopeUserId();

	/**
	 * Sets the scope user ID of this digest configuration.
	 *
	 * @param scopeUserId the scope user ID of this digest configuration
	 */
	public void setScopeUserId(long scopeUserId);

	/**
	 * Returns the scope user uuid of this digest configuration.
	 *
	 * @return the scope user uuid of this digest configuration
	 * @throws SystemException if a system exception occurred
	 */
	public String getScopeUserUuid() throws SystemException;

	/**
	 * Sets the scope user uuid of this digest configuration.
	 *
	 * @param scopeUserUuid the scope user uuid of this digest configuration
	 */
	public void setScopeUserUuid(String scopeUserUuid);

	/**
	 * Returns the summary length of this digest configuration.
	 *
	 * @return the summary length of this digest configuration
	 */
	public int getSummaryLength();

	/**
	 * Sets the summary length of this digest configuration.
	 *
	 * @param summaryLength the summary length of this digest configuration
	 */
	public void setSummaryLength(int summaryLength);

	/**
	 * Returns the activity types of this digest configuration.
	 *
	 * @return the activity types of this digest configuration
	 */
	@AutoEscape
	public String getActivityTypes();

	/**
	 * Sets the activity types of this digest configuration.
	 *
	 * @param activityTypes the activity types of this digest configuration
	 */
	public void setActivityTypes(String activityTypes);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DigestConfiguration digestConfiguration);

	public int hashCode();

	public CacheModel<DigestConfiguration> toCacheModel();

	public DigestConfiguration toEscapedModel();

	public DigestConfiguration toUnescapedModel();

	public String toString();

	public String toXmlString();
}